### ISSUE TITLE
error: implicit conversion changes signedness: 'enum vm_reg_name' to 'int'

### ISSUE THREAD

**Issue by jarrodconnolly** [moby/hyperkit#260]
Issue #246 was not fixed by the e499d90 commit referenced in marking it closed.

I am seeing this error on the latest master (c0dd463).

```
gen src/lib/dtrace.d
cc src/lib/vmm/intel/vmcs.c
cc src/lib/vmm/intel/vmx.c
src/lib/vmm/intel/vmx.c:1368:34: error: implicit conversion changes signedness: 'enum vm_reg_name' to 'int' [-Werror,-Wsign-conversion]
        error = vmx_getreg(vmx, vcpuid, reg, &val);
                ~~~~~~~~~~              ^~~
src/lib/vmm/intel/vmx.c:1419:40: error: implicit conversion changes signedness: 'enum vm_reg_name' to 'int' [-Werror,-Wsign-conversion]
        error = vmx_getdesc(vmx, vcpuid, vis->seg_name, &vis->seg_desc);
                ~~~~~~~~~~~              ~~~~~^~~~~~~~
2 errors generated.
make: *** [build/lib/vmm/intel/vmx.o] Error 1
```

λ  sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87

λ xcodebuild -version
Xcode 11.0
Build version 11A420a

λ cc --version
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by justincormack** [comment]
Interesting, I am not seeing that, but I have an older cc, will try updating XCode.

**Comment by justincormack** [comment]
Yes, this seems to error in XCode 11 only.

**Comment by justincormack** [comment]
This is really strange as enums are always signed...

**Comment by rn** [comment]
over on xhyve this was fixed via https://github.com/machyve/xhyve/commit/bbf81efe77f9df1d6cb6f33f62fc8481eedb5096

However in hyperkit there are a few more issue in the vsock implementation. For some reason, I don't quire under stand (yet) the CID is 64bit in some place.

**Comment by jarrodconnolly** [comment]
@justincormack Just a ping, any thoughts on getting #261 merged in to get building on OSX working again?

**Comment by townsend2010** [comment]
I don't understand why this is still an issue.  There are 2 PR's open (#261 & #266) that fixes this (#261 has been open for over 2 months now), yet is still remains an issue.  I mean this in the most respectful manner, but is hyperkit still an active project?

**Comment by djs55** [comment]
Hi, this is still an active project. Since it's heavily used on lots of machines we have to be a bit careful with changes, especially to core code. Hopefully we'll have time to do some review and testing soon!

**Comment by townsend2010** [comment]
hi @djs55,

Thanks so much for the reply!  Then I'll just wait and be patient :grin:

**Comment by srguglielmo** [comment]
Hello, any update on this? Builds are broken on `master` right now.

**Comment by djs55** [comment]
Fix has now been merged, thanks for your patience.
